FROM zenika/alpine-chrome:with-node

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD 1
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium-browser
WORKDIR /usr/src/app
COPY --chown=chrome package.json package-lock.json WhatsappMarketScrapper.js  ./
RUN npm install
EXPOSE 80
ENTRYPOINT ["node", "WhatsappMarketScrapper.js"]


